const TEST_CASE_DEFAULT = {
  input: "",
  expected: "",
  output: "",
  result: undefined,
  running: false
};

const LANGUAGES = [
  { label: "c", value: "c" },
  { label: "cpp", value: "cpp" },
  { label: "objective-c", value: "objective-c" },
  { label: "java", value: "java" },
  { label: "kotlin", value: "kotlin" },
  { label: "scala", value: "scala" },
  { label: "swift", value: "swift" },
  { label: "csharp", value: "csharp" },
  { label: "go", value: "go" },
  { label: "haskell", value: "haskell" },
  { label: "erlang", value: "erlang" },
  { label: "perl", value: "perl" },
  { label: "python", value: "python" },
  { label: "python3", value: "python3" },
  { label: "ruby", value: "ruby" },
  { label: "php", value: "php" },
  { label: "bash", value: "bash" },
  { label: "r", value: "r" },
  { label: "javascript", value: "javascript" },
  { label: "coffeescript", value: "coffeescript" },
  { label: "vb", value: "vb" },
  { label: "cobol", value: "cobol" },
  { label: "fsharp", value: "fsharp" },
  { label: "d", value: "d" },
  { label: "clojure", value: "clojure" },
  { label: "elixir", value: "elixir" },
  { label: "mysql", value: "mysql" },
  { label: "rust", value: "rust" },
  { label: "scheme", value: "scheme" },
  { label: "commonlisp", value: "commonlisp" },
  { label: "plain", value: "plain" }
];

const THEMES = [
  { label: "ambiance", value: "ambiance" },
  { label: "chaos", value: "chaos" },
  { label: "chrome", value: "chrome" },
  { label: "clouds", value: "clouds" },
  { label: "clouds_midnight", value: "clouds_midnight" },
  { label: "cobalt", value: "cobalt" },
  { label: "crimson_editor", value: "crimson_editor" },
  { label: "dawn", value: "dawn" },
  { label: "dracula", value: "dracula" },
  { label: "dreamweaver", value: "dreamweaver" },
  { label: "eclipse", value: "eclipse" },
  { label: "github", value: "github" },
  { label: "gob", value: "gob" },
  { label: "gruvbox", value: "gruvbox" },
  { label: "idle_fingers", value: "idle_fingers" },
  { label: "iplastic", value: "iplastic" },
  { label: "katzenmilch", value: "katzenmilch" },
  { label: "kr_theme", value: "kr_theme" },
  { label: "kuroir", value: "kuroir" },
  { label: "merbivore", value: "merbivore" },
  { label: "merbivore_soft", value: "merbivore_soft" },
  { label: "mono_industrial", value: "mono_industrial" },
  { label: "monokai", value: "monokai" },
  { label: "pastel_on_dark", value: "pastel_on_dark" },
  { label: "solarized_dark", value: "solarized_dark" },
  { label: "solarized_light", value: "solarized_light" },
  { label: "sqlserver", value: "sqlserver" },
  { label: "terminal", value: "terminal" },
  { label: "textmate", value: "textmate" },
  { label: "tomorrow", value: "tomorrow" },
  { label: "tomorrow_night_blue", value: "tomorrow_night_blue" },
  { label: "tomorrow_night_bright", value: "tomorrow_night_bright" },
  { label: "tomorrow_night_eighties", value: "tomorrow_night_eighties" },
  { label: "tomorrow_night", value: "tomorrow_night" },
  { label: "twilight", value: "twilight" },
  { label: "vibrant_ink", value: "vibrant_ink" },
  { label: "xcode", value: "xcode" }
];

const KEYBOARDS = [
  { label: "Normal", value: "" },
  { label: "Emacs", value: "emacs" },
  { label: "Sublime", value: "sublime" },
  { label: "Vim", value: "vim" }
];

export { TEST_CASE_DEFAULT, LANGUAGES, THEMES, KEYBOARDS };
